### PR TITLE
First step towards using bzlmod

### PR DESCRIPTION
**Pull request by hzeller**
* Move projects that are available already in https://registry.bazel.build/ from from load_external to MODULE.bazel.
 * This is not complete: there are probably more steps to simplify and clean-up after the first submit.
 * Switching to bzlmod broke making the compilation-db as the action hooks don't seem to work anymore ( xls/dev_tools//make-compilation-db.sh ). The used com_grail_bazel_compdb is not maintained anymore, so this needs to be updated to something more modern (hedronvision?). Since this is not actively needed in daily development (and I am the only one really using it), postponed for later.

Issues: #931

Also, needed to make Python rules to work well with --incompatible_default_to_explicit_init_py (bazelbuild/bazel#10076)

### CODE REVIEW

**Comment by hzeller** [comment]
Continuation of #1565

**Review by ericastor — COMMENTED** [review]
LGTM, though it sounds like we should wait for @cdleary to respond.

**Comment by proppy** [comment]
on macosx (14.6.1) when doing `bazel build //...`, there are a few warnings related to python:
```
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_8' from module 'protobuf': Toolchain 'python_3_8' from module 'grpc' already registered Python version 3.8 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_9' from module 'protobuf': Toolchain 'python_3_9' from module 'grpc' already registered Python version 3.9 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_10' from module 'protobuf': Toolchain 'python_3_10' from module 'grpc' already registered Python version 3.10 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_11' from module 'protobuf': Toolchain 'python_3_11' from module 'grpc' already registered Python version 3.11 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_12' from module 'protobuf': Toolchain 'python_3_12' from module 'grpc' already registered Python version 3.12 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_8' from module 'riegeli': Toolchain 'python_3_8' from module 'grpc' already registered Python version 3.8 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_9' from module 'riegeli': Toolchain 'python_3_9' from module 'grpc' already registered Python version 3.9 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_10' from module 'riegeli': Toolchain 'python_3_10' from module 'grpc' already registered Python version 3.10 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_11' from module 'riegeli': Toolchain 'python_3_11' from module 'grpc' already registered Python version 3.11 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_12' from module 'riegeli': Toolchain 'python_3_12' from module 'grpc' already registered Python version 3.12 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_11' from module 'rules_python': Toolchain 'python_3_11' from module 'grpc' already registered Python version 3.11 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_8' from module 'rules_fuzzing': Toolchain 'python_3_8' from module 'grpc' already registered Python version 3.8 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_9' from module 'rules_fuzzing': Toolchain 'python_3_9' from module 'grpc' already registered Python version 3.9 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_10' from module 'rules_fuzzing': Toolchain 'python_3_10' from module 'grpc' already registered Python version 3.10 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_11' from module 'rules_fuzzing': Toolchain 'python_3_11' from module 'grpc' already registered Python version 3.11 and has precedence
DEBUG: /private/var/tmp/_bazel_proppy/243779b655cdfb332dd4fc5af63d7557/external/rules_python~/python/private/bzlmod/python.bzl:46:10: WARNING: Ignoring toolchain 'python_3_12' from module 'rules_fuzzing': Toolchain 'python_3_12' from module 'grpc' already registered Python version 3.12 and has precedence
```
and a dependency missing on `sha265sum`:
```
ERROR: /Users/proppy/src/github.com/google/xls/xls/build_rules/tests/BUILD:81:23: Checking sha256sum on file: bazel-out/darwin_arm64-fastbuild/bin/xls/build_rules/tests/generated.x failed: (Exit 255): bash failed: error executing CheckSHA256SumFrozen command (from target //xls/build_rules/tests:generated_x_sha256sum_frozen) /bin/bash -c ... (remaining 1 argument skipped)
```

**Comment by hzeller** [comment]
* The Python warnings also happen on Linux, it is just an artifact of the dependency resolution in bzlmod which we can ignore.
  * `sha256sum`: maybe this is one of the instances in which bazel attempts to cut down on the shell utilities it supplies by default. Maybe we already compile sha256 from C-source somewhere anyway and should use that (but not in this change)
   * `llvm`: I suspect the equivalent has to be done before and after this change, so would not be influenced by this change.

But essentially what you say is looks good, regular SNAFU (in its original sense), but not impacted by this change.

**Comment by hzeller** [comment]
@cdleary : good to submit ?

**Comment by hzeller** [comment]
(Postponing for later)

**Pull request closed without merging**
