### PR TITLE
[examples] Integrating bazel rules hdl synthesis.

### PR DESCRIPTION
**Pull request by QuantamHD**
This integrates the synthesis rules into the XLS repo with the IDCT jpeg example.

### CODE REVIEW

**Comment by QuantamHD** [comment]
@nanavati

**Comment by QuantamHD** [comment]
@cdleary

**Comment by hongted** [comment]
How are eda tool dependencies handled?  Are they assumed to have been pre-built and located somewhere in the system path?  Should the readme be updated to include any needed changes for these targets?

**Comment by QuantamHD** [comment]
They are built from source in as part of bazel build similar to google3. Every tool used in the flow is built hermetically as part of the build. https://github.com/hdl/bazel_rules_hdl/tree/main/dependency_support

**Comment by QuantamHD** [comment]
@hongted If there aren't any concerns with this would you like to merge?

**Review by nanavati — APPROVED** [review]
Looks good to me. Thanks for integrating this!

**Pull request merged**
