### PR TITLE
[DSLX] Add functions that calculate the length of an array to stdlib

### PR DESCRIPTION
**Pull request by rw1nkler**
This PR adds functions to calculate the length of an array to XLS stdlib.

CC @proppy

### CODE REVIEW

**Comment by cdleary** [comment]
It's nice to have anything that can be done as a function in userspace be done that way, less stuff for the compiler to know / more being exercised without the special superpowers the frontend has access to. Looks great to have, thanks for adding!

**Comment by cdleary** [comment]
Oh actually, I realize @proppy 's point now -- we don't have a type that's polymorphic on signedness, e.g. what you really want to write is:

```
fn array_size<BITS: u32, ELEMS: u32, xN: signedness>(a: xN[BITS][ELEMS]) -> u32 {
  ELEMS
}
```

That does currently require builtin superpowers. Sorry I misunderstood the point! I'll get you that quickly.

**Comment by cdleary** [comment]
(Of course, feel free to use this impl in your implementation as a workaround until the builtin shows up.)

**Comment by cdleary** [comment]
Really appreciate the PR, but I think https://github.com/google/xls/commit/ab140b54173a8288db6cc211a021be58f211e9bc should do what you're looking for slightly better given what we discussed in this thread. LMK if you have any questions/concerns!

**Comment by rw1nkler** [comment]
I don't have any. Thank you for adding the built-in!

**Pull request closed without merging**
