### PR TITLE
[DSLX] Switch UseTreeEntry to an AstNode, make a cloner implementation.

### PR DESCRIPTION
**Pull request by cdleary**
Switch to AstNode for UseTreeEntry is per discussion with @richmckeever -- the rationale is, though we don't quite have it at the moment, in the future we may want to make an arbitrary matcher or replacer that was polymorphic on AstNode types, which makes it useful here to opt to reflect more structure of the AST in the node class form.

### CODE REVIEW

**Review by mikex-oss — APPROVED** [review]

**Comment by dplassgit** [comment]
This is failing compilation: `xls/dslx/type_system/type_info_to_proto.cc:55... enumeration value 'kUseTreeEntry' not handled in switch [-Werror,-Wswitch]`

**Comment by cdleary** [comment]
Oh, I think I see what happened, it's flagged as a warning but probably warnings-as-errors is on in google3 in some way that's not reflected in the OSS repo:
Screenshot 2024-12-11 at 11 11 26 AM

**Comment by cdleary** [comment]
Note this is ready to go and I updated the bazelrc to flag an error on this warning in the OSS build going forward.

**Comment by dplassgit** [comment]
Thanks, looks good.

**Pull request merged**
