### PR TITLE
modules/zstd: Add Sequence Executor

### PR DESCRIPTION
**Pull request by rw1nkler**
This PR adds Proc that performs ZSTD Sequence Execution as described in [rfc8878#section-3.1.1.5](https://datatracker.ietf.org/doc/html/rfc8878#section-3.1.1.5). The Proc is responsible for interpreting packets with Literals and Sequences obtained from the Procs that decode RAW, RLE, or Compressed blocks of data.

NOTE: this is based on https://github.com/google/xls/pull/1214 , please ignore commits from that branch when reviewing.
This is part of https://github.com/google/xls/issues/1211

### CODE REVIEW

**Comment by rw1nkler** [comment]
@hongted Here is a short description of the problem with looped connections:

`SequenceExecutor` is an example of Proc for which we observed problems during the Proc inlining step. During that step the tool shows a cycle in logic:
```
SUBCOMMAND: # //xls/modules/zstd:sequence_executor_verilog [action 'Optimizing IR file: bazel-out/k8-fastbuild/bin/xls/modules/zstd/sequence_executor_verilog.ir', configuration: 3d46003a2740b6027ad117c5193a361cf22b9845aa40b9d298dd905c9f83a639, execution platform: @local_config_platform//:host]                          
(cd /home/rwinkler/.cache/bazel/_bazel_rwinkler/d2cf6e52152dcda37d34f6b381369325/execroot/com_google_xls && \                                                 
  exec env - \                         
  /bin/bash -c 'bazel-out/k8-opt-exec-2B5CBBC6/bin/xls/tools/opt_main bazel-out/k8-fastbuild/bin/xls/modules/zstd/sequence_executor_verilog.ir  --inline_procs=true --top=__sequence_executor__SequenceExecutorZstd__SequenceExecutor_0__64_0_0_0_13_8192_65536_next 2>&1 >bazel-out/k8-fastbuild/bin/xls/modules/zstd/sequence_executor_verilog.opt.ir | tee bazel-out/k8-fastbuild/bin/xls/modules/zstd/sequence_executor_verilog.opt.log')
F0214 13:46:30.257837       3 node_iterator.cc:142] Check failed: f_->Accept(&cycle_checker) is OK (INTERNAL: Cycle detected: [status__1 -> concat.9782 -> and.9755 -> not.9735 -> and.9716 -> packet_valid -> ram_packet_valid -> SequenceExecutorZstd__SequenceExecutor_chandecl_xls_modules_zstd_sequence_executor_x_877_54_877_88_receive -> SequenceExecutorZstd__SequenceExecutor_chandecl_xls_modules_zstd_sequence_executor_x_877_54_877_88_receive_data -> SequenceExecutorZstd__SequenceExecutor_chandecl_xls_modules_zstd_sequence_executor_x_877_54_877_88_data_out -> SequenceExecutorZstd__SequenceExecutor_chandecl_xls_modules_zstd_sequence_executor_x_877_54_877_88_data_in -> output_data -> concat.9238 -> acc__10 -> converted__16 -> input_resp__1 -> input__1 -> SequenceExecutorZstd__SequenceExecutor_chandecl_xls_modules_zstd_sequence_executor_x_876_52_876_84_receive -> SequenceExecutorZstd__SequenceExecutor_chandecl_xls_modules_zstd_sequence_executor_x_876_52_876_84_receive_data -> SequenceExecutorZstd__SequenceExecutor_chandecl_xls_modules_zstd_sequence_executor_x_876_52_876_84_receive_fired -> SequenceExecutorZstd__SequenceExecutor_chandecl_xls_modules_zstd_sequence_executor_x_876_52_876_84_receive_activation_out -> SequenceExecutorZstd__SequenceExecutor_chandecl_xls_modules_zstd_sequence_executor_x_876_52_876_84_receive_not_stalled -> SequenceExecutorZstd__SequenceExecutor_chandecl_xls_modules_zstd_sequence_executor_x_876_52_876_84_receive_stall -> SequenceExecutorZstd__SequenceExecutor_chandecl_xls_modules_zstd_sequence_executor_x_876_52_876_84_valid -> SequenceExecutorZstd__SequenceExecutor_chandecl_xls_modules_zstd_sequence_executor_x_876_52_876_84_send_fired__1 -> do_read__1 -> mask__39 -> array_index.10144 -> read_reqs__1 -> concat.10093 -> and.9877 -> eq.9839 -> status__1])  
```

 Proc inlining step is a consequence of the `SequenceExecutor` architecture, in which communication with the RAMs takes place in multiple Procs:
seq_exec
Since it is impossible to rewrite the RAM interface "partially" (for example just read channels for a Proc that is responsible for handling reading from RAM) we had to inline the SequenceExecutor. In our case one of the inner Procs sends data to a input channel of `SequenceExecutor`. This loop is, as we believe, the source of problems. In normal scenario this kind of connection would be treated as FIFO. We wonder if this behavior is preserved during the proc inlining step for the looped channels.

**Comment by rw1nkler** [comment]
Thank you for confirmation. Is there any chance that #1018 will be resolved in the near future?

**Comment by proppy** [comment]
should we close this and focus on reviewing https://github.com/google/xls/pull/1315 ?

**Comment by rw1nkler** [comment]
Closing, as the review will happen in #1315

**Pull request closed without merging**
