### PR TITLE
Add simple RLE encoding pipeline

### PR DESCRIPTION
**Pull request by mtdudek**
This PR adds example of simple RLE encoding pipeline.
It uses RLE encoder from #974 and stream muxer form #1004.

Depends on:
- [ ] #1004 

Related: https://github.com/google/xls/issues/994

CC @proppy

### CODE REVIEW

**Comment by proppy** [comment]
Do want to land #974 first? or should we start reviewing now?

**Comment by tmichalak** [comment]
It seems we are close to merging #974, so that we can start reviewing this soon.

**Comment by proppy** [comment]
can we decouple this from #1012?

**Comment by mtdudek** [comment]
I'm closing this PR, as it's not necessary to have basic RLE implementation.

**Pull request closed without merging**
