### PR TITLE
[dependency_support] Update to latest rules_hdl repo.

### PR DESCRIPTION
**Pull request by QuantamHD**
This new release fixes an ncurses mirror issue.

### CODE REVIEW

**Comment by QuantamHD** [comment]
Need to wait for hdl/bazel_rules_hdl#52 to be merged.

**Comment by QuantamHD** [comment]
@hongted @nanavati This is ready to merge.

**Review by hongted — APPROVED** [review]
Thanks for looking into the CI failure and for the update!

**Comment by cdleary** [comment]
@googlebot rescan

**Comment by cdleary** [comment]
@googlebot rescan

**Pull request merged**
