### PR TITLE
modules/dbe - Lz4 decoder

### PR DESCRIPTION
**Pull request by rdob-ant**
This is an implementation of Lz4 decoder in DSLX and accompanying cocotb testsuite. Since Lz4 encoder reuses much of the code from this PR, I'd like to prepare it after this one is reviewed.

Some notes:
1. This relies on cocotb, so includes commits from #1057 . Once that is merged, this branch will be rebased.
2. DSLX implementation of decoder uses 1R1W RAM with 1 partition. Such configuration triggers a small bug (missing mask expansion) in examples/ram.x that this PR fixes.
3. It also includes reference decoder implementation in Python which is not used by the tests in the current PR, but will be needed for the upcoming Lz4 encoder PR.

### CODE REVIEW

**Comment by proppy** [comment]
Related to #995.

**Comment by proppy** [comment]
> This relies on cocotb, so includes commits from https://github.com/google/xls/pull/1057 . Once that is merged, this branch will be rebased.

Maybe we could move this to a separate PR, as it is not strictly required by the implementation (and not to block this being merged on the resolution of the discussions happening in #1057)

**Comment by proppy** [comment]
> Lz4 encoder reuses much of the code from this PR, I'd like to prepare it after this one is reviewed.

I'd be good to get the encoder and the decoder in the same PR, in order to be able to more effectively cross-review them. If it's challenging to send both at the same time, I think it'd be easier to review the encoder first.

**Comment by rdob-ant** [comment]
> can we get a separate PR for that (so that we can merge it earlier)

Opened #1078

**Comment by rdob-ant** [comment]
> Maybe we could move this to a separate PR, as it is not strictly required by the implementation (and not to block this being merged on the resolution of the discussions happening in https://github.com/google/xls/pull/1057)

We can, but since I wrote most of the tests in cocotb, I'm afraid without them the implementation may look "incomplete".

**Comment by rdob-ant** [comment]
> Do you plan to validate the dslx/ir/codegen versions against the python reference impl?

Yes, at least in one test I'm using Python decoder to decode (and thus validate) the output of DSLX encoder.

**Comment by rdob-ant** [comment]
Superseded by #1079 that includes both encoder and decoder.

**Pull request closed without merging**
