### PR TITLE
docs: remove generated docs

### PR DESCRIPTION
**Pull request by proppy**
follow-up to #1463

### CODE REVIEW

**Comment by proppy** [comment]
> Might be better to just remove docs in order for the copybara import to be a noop.

Done.

**Comment by cdleary** [comment]
@proppy do we just need to hit "merge" on this? Sorry, I was just unclear on whether the last message was looking for some action on our part

**Comment by proppy** [comment]
@cdleary yes, hitting merge should do the right thing 🤞

**Comment by cdleary** [comment]
@proppy I asked @meheff to be the one to hit the button so he could observe if there was any impact on syncs. :crossed_fingers:

**Pull request merged**
